# Generated by Django 5.1.1 on 2024-10-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_sizeperfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
