# Generated by Django 5.1.1 on 2024-09-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_chunk_id_telegram_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='size2',
        ),
    ]
