# Generated by Django 5.1.1 on 2024-10-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_file_uploading'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploadedSuccessfully',
            field=models.BooleanField(default=True),
        ),
    ]
