# Generated by Django 5.1.1 on 2024-10-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_notificacions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='id_telegram_message',
        ),
        migrations.AddField(
            model_name='chunk',
            name='encrypted_data',
            field=models.BinaryField(default=b''),
        ),
    ]
